version: '3'
services:
  traefik:
    image: traefik
    command: --api --docker
    ports:
      - '80:80' # The HTTP port
      - '8080:8080' # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    image: registry.online.lv/emdas/e2/eori
    labels:
      - traefik.docker.network=proxy
      - 'traefik.frontend.rule=Host:demo.lattelecom.io'
    ports:
      - '8080'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db

  db:
    image: postgres:11.1-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres_234
